### ISSUE TITLE
Remove optional dTiles dependencies

### ISSUE THREAD

**Issue by anita-steiner** [Caleydo/tdp_gene#108]
We want remove the following optional dTiles dependencies from the _package.json_:

https://github.com/Caleydo/tdp_gene/blob/15bd6e20dbd3d2274c82c080ec9ccd4aa7153b9d/package.json#L95-L98

After the interfaces SearchProvider interfaces have been moved to tdp_core (see datavisyn/dTiles#218), we need to update the imports here: 

https://github.com/Caleydo/tdp_gene/blob/20b0bb296cb9b580febe667dffc0e1977a6a1964/src/SearchProvider.ts#L3-L6

### Definition of Done

- [ ] The optional dTiles dependency is removed
- [ ] The build is successful

**Comment by anita-steiner** [comment]
depends on /datavisyn/dTiles#218

**Comment by thinkh** [comment]
Background information: Initially we wanted also remove the optional Ordino dependency. However, this is not easily possible, due to the following reasons:

* We import the TS typings _IStartMenuSection_ and _IStartMenuSectionOptions_ to define a custom Ordino start menu for gene ranking and visualizations
* tdp_gene should be usable without ordino (e.g., the visualization should be used in dTiles)
* ordino should be usable without tdp_gene (e.g., with a different data provider)

The last two reasons will always result in an optional dependency either in ordino or tdp_gene. The only option to avoid an/the optional ordino dependency is to avoid/remove the typings import and "blindly" implement the start menu section.

We will keep the optional Ordino dependency for now, as tpd_gene and ordino are both depending on tdp_core (and act as siblings in the dependency graph).
